//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsQuakesAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class earthquakesEntities : DbContext
    {
        public earthquakesEntities()
            : base("name=earthquakesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Quake> Quakes { get; set; }
    
        [DbFunction("earthquakesEntities", "tvf_Quakes_State_vs_State")]
        public virtual IQueryable<tvf_Quakes_State_vs_State_Result> tvf_Quakes_State_vs_State(string state1, string state2)
        {
            var state1Parameter = state1 != null ?
                new ObjectParameter("state1", state1) :
                new ObjectParameter("state1", typeof(string));
    
            var state2Parameter = state2 != null ?
                new ObjectParameter("state2", state2) :
                new ObjectParameter("state2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tvf_Quakes_State_vs_State_Result>("[earthquakesEntities].[tvf_Quakes_State_vs_State](@state1, @state2)", state1Parameter, state2Parameter);
        }
    
        public virtual ObjectResult<usp_Quakes_State_vs_State_Result> usp_Quakes_State_vs_State(string state1, string state2)
        {
            var state1Parameter = state1 != null ?
                new ObjectParameter("state1", state1) :
                new ObjectParameter("state1", typeof(string));
    
            var state2Parameter = state2 != null ?
                new ObjectParameter("state2", state2) :
                new ObjectParameter("state2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Quakes_State_vs_State_Result>("usp_Quakes_State_vs_State", state1Parameter, state2Parameter);
        }

        public System.Data.Entity.DbSet<CsQuakesAPI.tvf_Quakes_State_vs_State_Result> tvf_Quakes_State_vs_State_Result { get; set; }

        public System.Data.Entity.DbSet<CsQuakesAPI.usp_Quakes_State_vs_State_Result> usp_Quakes_State_vs_State_Result { get; set; }
    }
}
