//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsQuakesAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quake
    {
        public Nullable<System.DateTime> Event_DTG { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> depth { get; set; }
        public Nullable<double> mag { get; set; }
        public string magType { get; set; }
        public string nst { get; set; }
        public string gap { get; set; }
        public string dmin { get; set; }
        public string rms { get; set; }
        public string net { get; set; }
        public string Event_ID { get; set; }
        public Nullable<System.DateTime> Updated_DTG { get; set; }
        public string place { get; set; }
        public string type { get; set; }
        public string horizontalError { get; set; }
        public string depthError { get; set; }
        public string magError { get; set; }
        public string magNst { get; set; }
        public string status { get; set; }
        public string locationSource { get; set; }
        public string magSource { get; set; }
        public Nullable<int> Event_Year { get; set; }
        public Nullable<int> Event_Month { get; set; }
        public int Event_Day { get; set; }
        public Nullable<int> Event_Hour { get; set; }
        public Nullable<int> Event_Min { get; set; }
        public Nullable<int> Event_Sec { get; set; }
        public string cc { get; set; }
        public string admin1 { get; set; }
        public string admin2 { get; set; }
        public string name { get; set; }
        public Nullable<int> magInt { get; set; }
        public Nullable<int> mag0 { get; set; }
        public Nullable<int> mag1 { get; set; }
        public Nullable<int> mag2 { get; set; }
        public Nullable<int> mag3 { get; set; }
        public Nullable<int> mag4 { get; set; }
        public Nullable<int> mag5 { get; set; }
        public Nullable<int> mag6 { get; set; }
        public Nullable<int> mag7 { get; set; }
        public Nullable<int> mag8 { get; set; }
        public Nullable<int> mag9 { get; set; }
    }
}
